# Explicitly handles the prefix on the server side natively
server.servlet.context-path=/textr/api
spring.application.name=textr
server.port=8001
# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/ranadeepreddy
spring.datasource.username=ranadeepreddy
spring.datasource.password=ranadeepreddy
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA & Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 3. Logging (Optional but helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Liquibase Configuration
spring.liquibase.enabled=true
# Pointing to the external file directory we will mount in the Docker container
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
#spring.liquibase.liquibase-schema=liquibase_metadata
spring.liquibase.contexts=dev