# Connection Details
url=jdbc:postgresql://localhost:5432/ranadeepreddy
username=ranadeepreddy
password=ranadeepreddy
driver=org.postgresql.Driver

# Changelog File Location
changelog-file=src/main/resources/db/changelog/db.changelog-master.yaml

# Optional Defaults
default-schema-name=public
liquibase.schema-name=liquibase_metadata
contexts=dev
